# Generated by Django 5.2.1 on 2025-06-03 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comida',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='comidas/'),
        ),
    ]
