# Generated by Django 5.2.2 on 2025-06-05 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_delivery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='pagemento',
            new_name='pagamento',
        ),
    ]
